// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuVUAc5lSd3yNyEl7W_re_5iP7EsZCV_g',
    appId: '1:29441646006:web:8941d7345da5cd945d7517',
    messagingSenderId: '29441646006',
    projectId: 'new-app-d89bd',
    authDomain: 'new-app-d89bd.firebaseapp.com',
    storageBucket: 'new-app-d89bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7WDI5xygv-twHHhi1HqAitqP8DQIrkoU',
    appId: '1:29441646006:android:1c54a9e6ac3cd2495d7517',
    messagingSenderId: '29441646006',
    projectId: 'new-app-d89bd',
    storageBucket: 'new-app-d89bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFUjGIKDP2cAvdlbJEzMdLDw4kp6UA4-k',
    appId: '1:29441646006:ios:554a121bf2768a1d5d7517',
    messagingSenderId: '29441646006',
    projectId: 'new-app-d89bd',
    storageBucket: 'new-app-d89bd.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFUjGIKDP2cAvdlbJEzMdLDw4kp6UA4-k',
    appId: '1:29441646006:ios:554a121bf2768a1d5d7517',
    messagingSenderId: '29441646006',
    projectId: 'new-app-d89bd',
    storageBucket: 'new-app-d89bd.firebasestorage.app',
    iosBundleId: 'com.example.task2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuVUAc5lSd3yNyEl7W_re_5iP7EsZCV_g',
    appId: '1:29441646006:web:bb3639a589f2f3f15d7517',
    messagingSenderId: '29441646006',
    projectId: 'new-app-d89bd',
    authDomain: 'new-app-d89bd.firebaseapp.com',
    storageBucket: 'new-app-d89bd.firebasestorage.app',
  );
}
